name: cauliflower
description: "Cauliflower book."

publish_to: "none"
version: 0.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_markdown: ^0.7.3+1
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0
  widget_zoom: ^0.0.4
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/noto/NotoSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/noto/NotoSans-Italic-VariableFont_wdth,wght.ttf
          style: italic

  assets:
    - assets/content/
    - assets/images/
    - assets/images/personas/
    - assets/images/story/
    - assets/fonts/

# Command to generate the icons: `dart run flutter_launcher_icons`
flutter_launcher_icons:
  web:
    generate: true
  image_path: assets/images/app_icon.png
