name: storytext
description: "Interactive book application basis that combines elements of a messaging app with branching storylines."

publish_to: "none"
version: 0.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  shared_preferences: ^2.2.3
  yaml: ^3.1.2
  flutter_markdown: ^0.7.3+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/content.yaml
